AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable
  SuggestExtensions: false

Layout/LineLength:
  Max: 80

Metrics/AbcSize:
  Exclude:
    - 'lib/calendav/requests/*.rb'

Metrics/BlockLength:
  Exclude:
    - 'calendav.gemspec'
    - 'spec/**/*_spec.rb'
    - 'spec/acceptance/*.rb'

Metrics/MethodLength:
  Exclude:
    - 'lib/calendav/requests/*.rb'

Naming/RescuedExceptionsVariableName:
  PreferredName: error

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes
